version: "2"

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  varnish:
    build:
      context: .
    ports:
      - 9131:9131
    environment:
      VIRTUAL_HOST: whoami.127.0.0.1.xip.io
      VLC_BACKEND_HOST: backend
      VLC_BACKEND_PROBE_REQUEST_HOSTNAME: whoami.127.0.0.1.xip.io
    links:
      - backend:backend

  backend:
    image: emilevauge/whoami
    environment:
      VIRTUAL_HOST: whoami-origin.127.0.0.1.xip.io
