version: "2"
services:
  varnish:
    build:
      context: .
    ports:
      - "50001:6081"
      - "50002:6085"
    depends_on:
      - anon
      - auth
      - download
    environment:
      COOKIES: "true"
      COOKIES_WHITELIST: "(SESS[a-z0-9]+|SSESS[a-z0-9]+|NO_CACHE)"
      BACKENDS: "anon auth download"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      DASHBOARD_USER: "admin"
      DASHBOARD_PASSWORD: "admin"
      DASHBOARD_SERVERS: "varnish"
      DASHBOARD_DNS_ENABLED: "true"
    volumes:
      - ./custom/varnish:/srv/varnish
  anon:
    image: eeacms/hello
    environment:
      PORT: "8080"
  auth:
    image: eeacms/hello
    environment:
      PORT: "8080"
  download:
    image: eeacms/hello
    environment:
      PORT: "8080"